apiVersion: v1
kind: ConfigMap
metadata:
  name: client-env
data:
  env.js: |
    window.env = {
      API_BASE_URL: "http://aec54348b754141e08fdffe70beee5ad-354045000.us-east-1.elb.amazonaws.com/api"
    };
