apiVersion: v1
kind: Service
metadata:
  name: server-lb
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 5000 
  type: LoadBalancer