apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: 192881663819.dkr.ecr.us-east-1.amazonaws.com/server:v9
        ports: 
        - containerPort: 5000
        env:
          - name: DB_HOST
            value: database-1.cipya2cc6ud9.us-east-1.rds.amazonaws.com
          - name: DB_NAME
            value: dentaldb
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password